/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDepositVerifier,
  IDepositVerifierInterface,
} from "../../../contracts/interfaces/IDepositVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "uint256[5]",
        name: "input",
        type: "uint256[5]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDepositVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IDepositVerifierInterface {
    return new utils.Interface(_abi) as IDepositVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDepositVerifier {
    return new Contract(address, _abi, signerOrProvider) as IDepositVerifier;
  }
}
