/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITransactionVerifier,
  ITransactionVerifierInterface,
} from "../../../contracts/interfaces/ITransactionVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "uint256[10]",
        name: "input",
        type: "uint256[10]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITransactionVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): ITransactionVerifierInterface {
    return new utils.Interface(_abi) as ITransactionVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITransactionVerifier {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITransactionVerifier;
  }
}
