/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDepositVerifier } from "./IDepositVerifier";
export type { ITransactionVerifier } from "./ITransactionVerifier";
