/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "DepositVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DepositVerifier__factory>;
    getContractFactory(
      name: "IDepositVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDepositVerifier__factory>;
    getContractFactory(
      name: "ITransactionVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITransactionVerifier__factory>;
    getContractFactory(
      name: "IPoseidonHasher",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPoseidonHasher__factory>;
    getContractFactory(
      name: "MerkleTree",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleTree__factory>;
    getContractFactory(
      name: "PoseidonHasher",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonHasher__factory>;
    getContractFactory(
      name: "TransactionVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransactionVerifier__factory>;
    getContractFactory(
      name: "Wisp",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Wisp__factory>;
    getContractFactory(
      name: "WispToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WispToken__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "DepositVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DepositVerifier>;
    getContractAt(
      name: "IDepositVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDepositVerifier>;
    getContractAt(
      name: "ITransactionVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ITransactionVerifier>;
    getContractAt(
      name: "IPoseidonHasher",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPoseidonHasher>;
    getContractAt(
      name: "MerkleTree",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleTree>;
    getContractAt(
      name: "PoseidonHasher",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonHasher>;
    getContractAt(
      name: "TransactionVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TransactionVerifier>;
    getContractAt(
      name: "Wisp",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Wisp>;
    getContractAt(
      name: "WispToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WispToken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
